# Generated by Django 3.2.7 on 2023-03-27 17:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('customer_complaint', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('transantions_made', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('record_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('complated_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('status', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faults.customer')),
            ],
        ),
    ]
